# Generated by Django 5.1 on 2024-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
